# Price for entry in EUR
entry_fee: 10

# Number of participants allowed
max_participants: 50

# Registrations open?
registration_available: true

# Start date of LANparty
date: 2014-2-21

# Location of LANparty
location: "VUB Mandela"

# Time and date format
format: "%a %H:%M"

# Has the LANparty started?
on_lanparty: false

# Year
year: 2014

#name of the pricingdefault to be used when user is not part of any group
fallback_pricing_default_name: "FALLBACK_PRICING_DEFAULT"
fallback_pricing_default_transform: "cprice * p('1.75')"
