# Price for entry in EUR
entry_fee: 10

# Number of participants allowed
max_participants: 50

# Registrations open?
registration_available: true

# Start date of LANparty
start_datetime: 2014-02-14 18:00:00 +0100
end_datetime: 2014-02-16 18:00:00 +0100

# Location of LANparty
location: "VUB Mandela"

# Has the LANparty started?
on_lanparty: false

# Year
year: 2014

#name of the pricingdefault to be used when user is not part of any group
fallback_pricing_default_name: "FALLBACK_PRICING_DEFAULT"
fallback_pricing_default_transform: "cprice * p('1.75')"


testtime_in_gmt: 2014-02-21 18:00:00
