require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ClansController do

  # This should return the minimal set of attributes required to create a valid
  # Clan. As you add validations to Clan, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "tag" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ClansController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all clans as @clans" do
      clan = Clan.create! valid_attributes
      get :index, {}, valid_session
      assigns(:clans).should eq([clan])
    end
  end

  describe "GET show" do
    it "assigns the requested clan as @clan" do
      clan = Clan.create! valid_attributes
      get :show, {:id => clan.to_param}, valid_session
      assigns(:clan).should eq(clan)
    end
  end

  describe "GET new" do
    it "assigns a new clan as @clan" do
      get :new, {}, valid_session
      assigns(:clan).should be_a_new(Clan)
    end
  end

  describe "GET edit" do
    it "assigns the requested clan as @clan" do
      clan = Clan.create! valid_attributes
      get :edit, {:id => clan.to_param}, valid_session
      assigns(:clan).should eq(clan)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Clan" do
        expect {
          post :create, {:clan => valid_attributes}, valid_session
        }.to change(Clan, :count).by(1)
      end

      it "assigns a newly created clan as @clan" do
        post :create, {:clan => valid_attributes}, valid_session
        assigns(:clan).should be_a(Clan)
        assigns(:clan).should be_persisted
      end

      it "redirects to the created clan" do
        post :create, {:clan => valid_attributes}, valid_session
        response.should redirect_to(Clan.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved clan as @clan" do
        # Trigger the behavior that occurs when invalid params are submitted
        Clan.any_instance.stub(:save).and_return(false)
        post :create, {:clan => { "tag" => "invalid value" }}, valid_session
        assigns(:clan).should be_a_new(Clan)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Clan.any_instance.stub(:save).and_return(false)
        post :create, {:clan => { "tag" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested clan" do
        clan = Clan.create! valid_attributes
        # Assuming there are no other clans in the database, this
        # specifies that the Clan created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Clan.any_instance.should_receive(:update_attributes).with({ "tag" => "MyString" })
        put :update, {:id => clan.to_param, :clan => { "tag" => "MyString" }}, valid_session
      end

      it "assigns the requested clan as @clan" do
        clan = Clan.create! valid_attributes
        put :update, {:id => clan.to_param, :clan => valid_attributes}, valid_session
        assigns(:clan).should eq(clan)
      end

      it "redirects to the clan" do
        clan = Clan.create! valid_attributes
        put :update, {:id => clan.to_param, :clan => valid_attributes}, valid_session
        response.should redirect_to(clan)
      end
    end

    describe "with invalid params" do
      it "assigns the clan as @clan" do
        clan = Clan.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Clan.any_instance.stub(:save).and_return(false)
        put :update, {:id => clan.to_param, :clan => { "tag" => "invalid value" }}, valid_session
        assigns(:clan).should eq(clan)
      end

      it "re-renders the 'edit' template" do
        clan = Clan.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Clan.any_instance.stub(:save).and_return(false)
        put :update, {:id => clan.to_param, :clan => { "tag" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested clan" do
      clan = Clan.create! valid_attributes
      expect {
        delete :destroy, {:id => clan.to_param}, valid_session
      }.to change(Clan, :count).by(-1)
    end

    it "redirects to the clans list" do
      clan = Clan.create! valid_attributes
      delete :destroy, {:id => clan.to_param}, valid_session
      response.should redirect_to(clans_url)
    end
  end

end
